#!/usr/local/bin/python3

import base64
import binascii
import sys

#import cgitb
#cgitb.enable()

image_dir = '/students/xxx/public_html/images/'
f = open(image_dir + 'external-link-icon.gif', 'rb')
bytes = f.read()

data = open(image_dir + 'python-logo-master-v3-TM-flattened.png', 'rb').read()

ff = open(image_dir + 'python_logo_copy.png', 'wb')
ff.write(data)

encoded2 = str(base64.b64encode(bytes))
encoded2 = str(base64.b64encode(bytes)).replace(r'\n', '')
encoded2 = str(binascii.b2a_base64(bytes)).replace(r'\n', '')
for_css = str(encoded2)[2:-1].strip()

print('Content-type:text/html\n')

print('''<!DOCTYPE html>
<html>
    <head>
        <title>My Base64 Rockin Image!!</title>
        <style type="text/css">
        body {background-color:white;font-style:none;font-weight:normal;font-family:Gill Sans, Helvetica, Arial, sans-serif;font-weight:bold;font-size:30px;color:#c00;
        text-shadow: 0 0 2px black,0px 0px 8px white;
        background:url(data:image/gif;base64,%s);text-align:center}
        h1 {font-size:72px;font-weight:bold}
        h2 {font-weight:normal}
        div {font-family:Arial;font-size:30px;color:black;text-shawdow:none;background-color:white;width:440px;margin:0 auto}.source {width:960px}
        </style>
    </head>
<body>
<h1>Hello!</h1>
<div>
Background image is in the css as base64-encoded data
</div>
<h2> A copy</h2>
<img src="/xxx/images/python_logo_copy.png" alt="Python logo">
<br>
<h2>Image generated on the fly by Python!</h2>
<img src="/xxx/cs131a/exercise5.2.cgi" alt="Python Logo generated by Python script">

<p>Solutions for Exercise 5.1 and 5.2</p>
<ul><li><a href="http://hills.ccsf.edu/xxx/cs131a/exercise5.1.cgi">Exercise 5.1 Solution</a></li>
<li><a href="http://hills.ccsf.edu/xxx/cs131a/exercise5.2.cgi">Exercise 5.2 Solution</a></li>
        </ul>
    </body>
</html>''' % for_css)
    # SOURCE CODE
    ##PRINT SOURCE CODE
